export default [
  {
    name: 'Dados Pessoal 1',
    components: [
      {
        name: 'Input',
        key: 'name',
        title: 'Nome',
        placeholder: 'Nome como no documento',
      },
      {
        name: 'Input',
        key: 'last_name',
        title: 'Sobrenome',
        placeholder: 'Sobrenome como no documento',
      },
      {
        name: 'Input',
        key: 'email',
        title: 'E-mail',
        placeholder: 'exemplo@email.com',
      },
      {
        name: 'InputMask',
        key: 'phone1',
        title: 'Telefone',
        placeholder: '(00) 0000-0000',
        mask: '([00]) [00000]-[0000]',
        type: 'numeric',
      },
      {
        name: 'InputMask',
        key: 'phone2',
        title: 'Celular',
        placeholder: '(00) 0000-0000',
        mask: '([00]) [00000]-[0000]',
        type: 'numeric',
      },
      {
        name: 'InputMask',
        key: 'birth_date',
        title: 'Data de Nascimento',
        placeholder: '00/00/0000',
        mask: '[00]/[00]/[0000]',
        type: 'numeric',
      },
    ],
  },
  {
    name: 'Dados Pessoal 2',
    components: [
      {
        name: 'Picker',
        key: 'civil_state',
        title: 'Estado Civil',
        options: ['Solteiro(a)', 'Casado(a)', 'Viuva(o)'],
      },
      {
        name: 'Radio',
        key: 'genre',
        title: 'Genero',
        opt1: 'Masculino',
        opt2: 'Feminino',
      },
      {
        name: 'InputMask',
        key: 'height',
        title: 'Altura',
        placeholder: '0.00',
        mask: '[0].[00]',
        type: 'numeric',
      },
      {
        name: 'InputMask',
        key: 'weight',
        title: 'Peso',
        placeholder: '00.0',
        mask: '[00].[0]',
        type: 'numeric',
      },
      {
        name: 'Radio',
        key: 'professional_situation',
        title: 'Ativo em plena atividade profissional',
        opt1: 'SIM',
        opt2: 'NÃO',
      },
      {
        name: 'Input',
        key: 'income',
        title: 'Remuneração mensal (R$)',
        placeholder: '1865',
        type: 'numeric',
      },
    ],
  },
  {
    name: 'Endereço',
    components: [
      {
        name: 'Input',
        key: 'city',
        title: 'Cidade',
        placeholder: 'São Jose dos Campos',
      },
      {
        name: 'Input',
        key: 'uf',
        title: 'Estado',
        placeholder: 'São Paulo',
      },
      {
        name: 'Input',
        key: 'neighborhood',
        title: 'Bairro',
        placeholder: 'São João',
      },
      {
        name: 'Input',
        key: 'address_number',
        title: 'Numero',
        type: 'numeric',
        placeholder: '000',
      },
      {
        name: 'InputMask',
        key: 'cep',
        title: 'CEP',
        placeholder: '00000-000',
        mask: '[00000]-[000]',
        type: 'numeric',
      },
    ],
  },
  {
    name: 'Dependentes',
    components: [
      {
        name: 'Miniform',
        key: 'dependents',
        limit: 5,
        components: [
          {
            name: 'Input',
            key: 'name',
            title: 'Nome',
            placeholder: 'Nome como no documento',
          },
          {
            name: 'InputMask',
            key: 'cpf',
            title: 'CPF',
            mask: '[000].[000].[000]-[00]',
            type: 'numeric',
            placeholder: '000.000.000-00',
          },
          {
            name: 'Input',
            key: 'kinship',
            title: 'Parentesco',
            placeholder: 'Filho',
          },
          {
            name: 'InputMask',
            key: 'participation',
            title: 'Participação %',
            mask: '[00]%',
            type: 'numeric',
            placeholder: '00%',
          },
        ],
      },
    ],
  },
  {
    name: 'Documentos',
    components: [
      {
        name: 'InputMask',
        key: 'cpf',
        title: 'CPF',
        mask: '[000].[000].[000]-[00]',
        type: 'numeric',
        placeholder: '000.000.000-00',
      },
      /*  {
        name: 'Picker',
        key: 'rg_type',
        title: 'Tipo de RG(Civil ou militar)',
        options: ['Civil', 'Militar'],
      }, */
      {
        name: 'Radio',
        key: 'rg_type',
        title: 'Tipo de RG',
        opt1: 'Civil',
        opt2: 'Militar',
      },
      {
        name: 'InputMask',
        key: 'rg',
        title: 'RG',
        mask: '[0000]-[000]',
        type: 'numeric',
        placeholder: '0000-000',
        conditional: 'Civil',
        dependency: 'rg_type',
      },
      {
        name: 'InputMask',
        key: 'rg',
        title: 'RG',
        mask: '[000000000]-[0]',
        type: 'numeric',
        placeholder: '000000000-0',
        conditional: 'Militar',
        dependency: 'rg_type',
      },
      {
        name: 'Image',
        key: 'doc',
        title: 'Imagem do documento (CNH)',
        crop: true,
      },
      {
        name: 'Image',
        key: 'face',
        title: 'Uma foto do seu rosto',
        crop: false,
      },
    ],
  },
  {
    name: 'Documentos do Veiculo',
    components: [
      {
        name: 'InputMask',
        key: 'via',
        title: 'Via',
        mask: '[0]',
        type: 'numeric',
        placeholder: '2',
      },
      {
        name: 'InputMask',
        key: 'renavan',
        title: 'Cod. Renavan',
        mask: '[000000000]',
        type: 'numeric',
        placeholder: '000000000',
      },
      {
        name: 'InputMask',
        key: 'truck_plate',
        title: 'Placa do caminão',
        mask: '[AAA]-[0A00]',
        placeholder: 'ABC-0A00',
      },
      {
        name: 'Input',
        key: 'truck_brand',
        title: 'Marca do caminhão',
        placeholder: 'Mercedes',
      },
      {
        name: 'Input',
        key: 'truck_model',
        title: 'Modelo do caminhão',
        placeholder: 'Atego',
      },
      {
        name: 'Input',
        key: 'truck_color',
        title: 'Cor do caminhão',
        placeholder: 'Prata',
      },
      {
        name: 'InputMask',
        key: 'truck_date',
        title: 'Ano do caminhão',
        placeholder: '00/00/0000',
        mask: '[00]/[00]/[0000]',
        type: 'numeric',
      },
    ],
  },
  {
    name: 'Imagens doc do Veiculo',
    components: [
      {
        name: 'Image',
        key: 'doc_truck_front',
        title: 'Imagem da FRENTE do documento do caminhão',
        crop: true,
      },
      {
        name: 'Image',
        key: 'doc_truck_behind',
        title: 'Imagem da parte de TRAS do documento do caminhão',
        crop: true,
      },
    ],
  },
];
